### ISSUE TITLE
Please release luabidi 0.3

### ISSUE THREAD

**Issue by jspitz** [bidi-tex/luabidi#2]
Luabidi is broken since 3 years now. The issue is fixed (see https://github.com/reutenauer/polyglossia/issues/215) in the repo, but not on CTAN.

Please release this ASAP to make luabidi (and polyglossia with RTL scripts and LuaTeX) usable again.

**Comment by reutenauer** [comment]
Hi Jürgen,

I am aware of that, I’m currently travelling for TUG’19 and will take care of it, at the latest when I’m back in one week.

**Comment by jspitz** [comment]
Like now ;-)?

**Comment by reutenauer** [comment]
Or tomorrow ;-) I'm in the middle of a move, should have more time tomorrow when I'm done.

**Comment by reutenauer** [comment]
Done.  Please give it a day or two to be processed by CTAN’s upload managers, and an additional 24 hours to appear on CTAN mirrors.

**Comment by jspitz** [comment]
Thank you so much, Arthur.

**Comment by jspitz** [comment]
Done.
